# Generated by Django 4.0.4 on 2022-05-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-checkout_time']},
        ),
    ]
