# Generated by Django 4.0.4 on 2022-05-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_alter_checkout_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={},
        ),
    ]
